server:
  port: 7001

# 通义千问配置
qwen:
  sdk:
    config:
     enable: true
     api-key:

# b站配置
bilibili:
  chatbot:
    plus:
      config:
        url: "https://api.vc.bilibili.com"
        send_image_url: "https://api.bilibili.com"
        login_id:
        cookie:
        csrf:
        session_type: 1
        size: 100
        mobiApp: "web"

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml