server:
  port: 7001

# Http客户端配置
okhttpclient:
  config:
    connectTimeOut: 60
    writeTimeOut: 60
    readTimeOut: 60

# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy

# 通义千问配置
qwen:
  sdk:
    config:
      enable: true
      api-key:
      analysis_video_url: "https://www.hhlqilongzhu.cn"

# b站配置
bilibili:
  chatbot:
    plus:
      config:
        url: "https://api.vc.bilibili.com"
        send_image_url: "https://api.bilibili.com"
        send_video_url: "https://member.bilibili.com"
        login_id:
        cookie:
        csrf:
        session_type: 1
        size: 100
        mobiApp: "web"
        cover:

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml